c:
  mode: train
  resume: true
  resume_optimizer: false
  ckpt_path: /SharedData/dengzy/Quarl/experiment/ppo-new/outputs/h100_nam_pretrain_6small_cluster_20260816_183726/ckpts/iter_576.pt
  load_non_ddp_ckpt: true
  load_best_info: false
  best_info_dir: outputs/2022-06-26/08-45-11/sync_dir
  gpus:
  - 0
  ddp_port: 33917
  omp_num_threads: 4
  seed: 98765
  wandb:
    en: false
    offline: false
    entity: quartz
    project: PPO-Finetune-04
  gate_set:
  - h
  - cx
  - x
  - rz
  - add
  ecc_file: ../ecc_set/nam_ecc.json
  no_increase: false
  include_nop: true
  num_gate_types: 40
  input_graphs:
  - name: barenco_tof_3
    path: ../circs/nam_circs/barenco_tof_3.qasm
  gnn_type: QGNN
  gate_type_embed_dim: 16
  gnn_num_layers: 6
  gnn_hidden_dim: 128
  gnn_output_dim: 128
  gin_num_mlp_layers: 2
  gin_learn_eps: false
  gin_neighbor_pooling_type: sum
  gin_graph_pooling_type: none
  actor_hidden_size: 256
  critic_hidden_size: 128
  gamma: 0.95
  entropy_coeff: 0.02
  eps_clip: 0.2
  softmax_temp_en: true
  hit_rate: 0.9
  mp_start_method: spawn
  obs_per_agent: 0
  cost_type: gate_count
  nop_stop: true
  invalid_reward: -1.0
  max_extra_cost: 6
  limit_total_gate_count: false
  batch_inference: true
  dyn_eps_len: true
  max_eps_len: 600
  min_eps_len: 20
  greedy_sample: true
  agent_collect: true
  agent_batch_size: 64
  subgraph_opt: true
  xfer_pred_layers: 1
  max_iterations: 591
  num_eps_per_iter: 64
  mini_batch_size: 4800
  k_epochs: 5
  lr_gnn: 0.0
  lr_actor: 0.0
  lr_critic: 0.0
  lr_scheduler: none
  lr_start_factor: 0.1
  lr_warmup_epochs: 15
  update_policy_interval: 1
  save_ckpt_interval: 1
  time_budget: ''
  wandb_run_name_suffix: ''
  best_graph_output_dir: best_graphs
  output_full_seq: false
  full_seq_path: ''
  vmem_perct_limit: 70.0
